# Generated by Django 2.2.3 on 2020-08-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_current',
            field=models.ForeignKey(default=models.DecimalField(decimal_places=2, max_digits=6), on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.Bid'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
