# Generated by Django 2.2.3 on 2020-08-19 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200819_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_current',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.Bid'),
        ),
    ]
