# Generated by Django 2.2.3 on 2020-08-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200819_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.BooleanField(null=True),
        ),
    ]
